spring:
  datasource:
    url: jdbc:sqlserver://cc-app.database.windows.net:1433;database=cc-app;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: cc-app
    password: Cloud-Computing@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 8081
